(()=>{'use strict';const d=window.ILMETEO_DATA, $=s=>document.querySelector(s);if(!d)return;const city=d.milano||d.bologna;document.querySelectorAll('select,.search input,.search button,[data-hour]').forEach(el=>el.disabled=false);
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let tempUnit='C';
function convert(){document.querySelectorAll('[data-celsius]').forEach(el=>{const c=Number(el.dataset.celsius),v=tempUnit==='C'?c:Math.round((c*9/5+32)*10)/10;el.textContent=String(v).replace('.',',')+'°'+tempUnit;});}
$('.search')?.addEventListener('submit',e=>{e.preventDefault();const q=$('#city-search').value.trim(),p=$('#search-note');if(/^milano$/i.test(q)){location.href='milano.html';return;}p.replaceChildren();const msg=document.createElement('span');msg.textContent=q?'La copia locale contiene le previsioni di Milano. Per altre località consulta iLMeteo.':'Scrivi una località. In questa copia è disponibile Milano.';p.append(msg);const local=document.createElement('a');local.href='milano.html';local.className='link';local.textContent='Apri Milano';p.append(local);if(q){const ext=document.createElement('a');ext.href='https://www.ilmeteo.it/';ext.className='link';ext.textContent='Cerca sul sito ufficiale';p.append(ext);}$('#city-search').setAttribute('aria-invalid','true');});
$('#city-search')?.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#search-note').replaceChildren();$('#city-search').removeAttribute('aria-invalid');}});
$('#city-search')?.addEventListener('input',()=>{$('#city-search').removeAttribute('aria-invalid');$('#search-note').replaceChildren();});
document.querySelectorAll('[data-zoom]').forEach(a=>a.addEventListener('click',e=>{const dialog=$('#map-dialog');if(!dialog?.showModal)return;e.preventDefault();const caption=a.dataset.caption;const zoom=$('#zoom-map');zoom.hidden=false;delete zoom.dataset.failed;if(zoom.nextElementSibling?.classList.contains('image-error'))zoom.nextElementSibling.remove();zoom.src=a.getAttribute('href');$('#zoom-map').alt=caption;$('#map-caption').textContent=caption;dialog.showModal();}));
function showHour(id,details){const r=city.hourly.find(r=>r.id===id);if(!r)return;document.querySelectorAll('[data-row]').forEach(el=>el.classList.toggle('selected',el.dataset.row===id));document.querySelectorAll('.hour-pick').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.hour===id)));$('#selected-time').textContent=(r.date===city.date?'Ore ':new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(r.date+'T12:00:00Z'))+' · ')+r.time+(r.intervalHours===3?' · 3 h':'');$('#selected-condition').textContent=r.condition;$('#selected-temp').innerHTML='<span data-celsius="'+r.temperatureC+'"></span>';const cell=d.brand.weatherIconCells[r.symbol];$('#selected-symbol').innerHTML=cell?'<span class="weather-symbol weather-symbol-generated" data-weather-symbol="'+safe(r.symbol)+'" aria-hidden="true" style="background-position:'+(cell.column*50)+'% '+(cell.row*100)+'%"></span>':'';const buttons=[...document.querySelectorAll('.hour-pick')],i=buttons.findIndex(x=>x.dataset.hour===id);if(i>=0){$('.hour-line').style.setProperty('--mark-index',String(i));}const box=$('#hour-detail');if(box){box.innerHTML='<h2 tabindex="-1">Milano · '+safe(r.time)+' · '+safe(new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(r.date+'T12:00:00Z')))+' · intervallo '+r.intervalHours+' h</h2><p class="note">Valori del dettaglio originale, con le unità pubblicate dalla fonte.</p><dl class="detail-grid">'+r.detail.fields.map(f=>'<div><dt>'+safe(f.label)+'</dt><dd>'+safe(f.value)+'</dd></div>').join('')+'<div><dt>Temperatura percepita · tabella</dt><dd>'+safe(String(r.feelsLikeC).replace('.',','))+'°C</dd></div></dl>';if(details){box.hidden=false;box.querySelector('h2').focus();}}convert();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-hour]');if(b)showHour(b.dataset.hour,b.hasAttribute('data-show-detail'));});
$('#temp-unit')?.addEventListener('change',e=>{tempUnit=e.target.value;convert();});
$('#wind-unit')?.addEventListener('change',e=>{document.querySelectorAll('[data-kmh]').forEach(el=>{const k=Number(el.dataset.kmh);el.textContent=e.target.value==='kn'?(Math.round(k/1.852*10)/10).toLocaleString('it-IT')+' nodi':k+' km/h';});});
const interval=$('#hour-interval');interval?.addEventListener('change',()=>{document.querySelectorAll('[data-interval]').forEach(el=>el.hidden=el.dataset.interval!==interval.value);$('#interval-status').textContent='Altre tabelle: intervalli di '+interval.value+' ore. La tabella iniziale mantiene i primi quattro orari a un’ora. Ogni riga conserva il proprio dettaglio.';});
const day=$('#forecast-day');day?.addEventListener('change',()=>{const x=city.daily.find(x=>x.date===day.value);if(!x)return;$('#day-summary').innerHTML='<p>'+safe(new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(x.date+'T12:00:00Z')))+' · minima <span data-celsius="'+x.minimumC+'"></span> · massima <span data-celsius="'+x.maximumC+'"></span> · attendibilità '+(x.forecastReliabilityPercent===null?'non fornita':x.forecastReliabilityPercent+'%')+'</p><p class="note">'+(x.hourly.length?'Sono disponibili soltanto le ore elencate nelle tabelle dell’edizione acquisita.':'Le previsioni orarie di questo giorno non sono acquisite. Il riepilogo giornaliero resta disponibile.')+'</p>';convert();});
function filterMaps(){const family=$('#map-family'),period=$('#map-period');if(!family||!period)return;const f=d.home.mapFamilies.find(x=>x.id===family.value);if(f&&period.value!=='all'&&!f.maps.some(x=>x.id===period.value)){period.value=f.maps[0].id;$('#map-status').textContent='Per '+f.label+' è disponibile '+f.maps[0].label+'.';}else $('#map-status').textContent=(f?.label||'Tutte le mappe')+' · '+period.selectedOptions[0].textContent;document.querySelectorAll('[data-map-family]').forEach(el=>el.hidden=(family.value!=='all'&&el.dataset.mapFamily!==family.value)||(period.value!=='all'&&el.dataset.mapPeriod!==period.value));}
$('#map-family')?.addEventListener('change',filterMaps);$('#map-period')?.addEventListener('change',filterMaps);
$('#national-period')?.addEventListener('change',e=>{document.querySelectorAll('[data-national-period]').forEach(el=>el.hidden=e.target.value!=='all'&&el.dataset.nationalPeriod!==e.target.value);$('#period-status').textContent=e.target.selectedOptions[0].textContent;});
document.querySelectorAll('img').forEach(img=>{const fail=()=>{if(img.dataset.failed)return;img.dataset.failed='true';img.hidden=true;const p=document.createElement('p');p.className='image-error';p.textContent=img.alt?'Immagine non disponibile: '+img.alt:'Immagine non disponibile';img.after(p);};img.addEventListener('error',fail);if(img.complete&&img.naturalWidth===0&&img.getAttribute('src'))fail();});
if(interval){document.querySelectorAll('[data-interval]').forEach(el=>el.hidden=el.dataset.interval!==interval.value);}filterMaps();
document.querySelectorAll('.radar-scale').forEach(el=>{const frame=el.querySelector('.radar-frame'),resize=()=>{frame.style.transform='scale('+Math.min(1,el.clientWidth/425)+')';};resize();if(window.ResizeObserver)new ResizeObserver(resize).observe(el);});
})();
