import {weatherIcon, searchIcon} from './redesign-icons.mjs';
import sizes from './asset-sizes.json' with {type:'json'};
export const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const date = (v,short=false) => new Intl.DateTimeFormat('it-IT',{weekday:short?undefined:'long',day:'numeric',month:'long',year:short?undefined:'numeric',timeZone:'UTC'}).format(new Date(v+'T12:00:00Z'));
export const temp = v => `<span data-celsius="${v}">${String(v).replace('.',',')}°C</span>`;
export const details=(title,body,open=false)=>`<details class="collapse collapse-arrow disclosure"${open?' open':''}><summary class="collapse-title">${esc(title)}</summary><div class="collapse-content">${body}</div></details>`;
export const link = l => l.href?`<a class="link" href="${esc(l.href)}">${esc(l.label)}${l.availability==='external'?'<span class="external-note"> · sito ufficiale</span>':''}</a>`:`<span>${esc(l.label)} <small>— non disponibile nella copia</small></span>`;
export const symbol=(d,id)=>weatherIcon(id);
export const figure=(a,caption,cls='')=>`<figure class="map-figure ${cls}"><a class="map-open" href="${esc(a.src)}" data-zoom data-caption="${esc(caption)}" aria-label="Ingrandisci: ${esc(caption)}"><img src="${esc(a.src)}" ${sizes[a.src]?`width="${sizes[a.src].width}" height="${sizes[a.src].height}"`:""} alt="${esc(a.alt&&a.alt!=='Mappa'?a.alt:caption)}" loading="${cls==='compact-map'||cls==='hero-map'?'eager':'lazy'}"></a><a class="link map-zoom" href="${esc(a.src)}" data-zoom data-caption="${esc(caption)}">Ingrandisci mappa</a>${a.originalSrc?`<a class="link map-original" href="${esc(a.originalSrc)}">Vedi mappa originale</a>`:''}<figcaption>${esc(caption)}</figcaption></figure>`;
export const h={esc,date,temp,details,link,symbol,figure};
export function header(d,page){return `<a class="skip-link" href="#contenuto">Vai al contenuto</a><header><div class="site-header"><a href="index.html" aria-label="iLMeteo · Home"><img class="brand" src="assets/brand/ilmeteo-modern-v1.png" width="74" height="74" alt="iLMeteo"></a><form class="search" action="milano.html" role="search"><label class="sr-only" for="city-search">Cerca una località</label><input class="input" id="city-search" disabled name="q" type="search" list="local-places" value="${page==='milano'?'Milano':''}" placeholder="Cerca una località" aria-describedby="search-note" autocomplete="off"><button class="btn btn-ghost" type="submit" disabled aria-label="Cerca">${searchIcon}</button><datalist id="local-places"><option value="Milano"></option></datalist><p id="search-note" class="search-feedback" role="status"></p></form><nav aria-label="Pagine principali">${[['index','Home'],['milano','Milano'],['domani','Domani']].map(([f,l])=>`<a href="${f}.html"${page===f||(page==='home'&&f==='index')?' aria-current="page"':''}>${l}</a>`).join('')}</nav></div><noscript><p class="edition">La ricerca e i filtri richiedono JavaScript. Puoi aprire Milano dai collegamenti e leggere tutti i dati e i dettagli originali.</p></noscript><p class="edition">${page==='milano'?'Milano acquisita il 9 ottobre 2026':'Home e Italia acquisite l’8 ottobre 2026'} · copia didattica congelata</p></header>`;}
export function shell(d,page,title,body,extra=''){return `<!doctype html><html lang="it" data-theme="ilmeteo"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta http-equiv="Content-Security-Policy" content="default-src 'self' data:; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'none'; object-src 'none'; base-uri 'none'"><title>${esc(title)} · iLMeteo, edizione ${page==='milano'?'9':'8'} ottobre 2026</title><link rel="stylesheet" href="style.css"><script defer src="runtime.js"></script><script defer src="app.js"></script></head><body data-page="${page}">${header(d,page)}<main id="contenuto" class="page" tabindex="-1">${(body+extra).replaceAll('<select class="select"','<select disabled class="select"').replaceAll(' data-hour=',' disabled data-hour=')}</main><footer class="site-footer"><p>${esc(d.shared.footer.text.split(' Privacy e Cookie Policy')[0])}</p><nav aria-label="Informazioni societarie">${d.shared.footer.links.map(link).join('')}</nav><p>Materiali iLMeteo e rispettivi autori · esercitazione locale · <a class="link" href="../index.html">Confronta originale e redesign</a></p></footer><dialog class="modal" id="map-dialog" aria-labelledby="map-caption"><div class="modal-box"><form method="dialog"><button class="btn close-map" aria-label="Chiudi mappa">Chiudi</button></form><img id="zoom-map" src="../assets/plates/national-map.png" alt="" loading="lazy"><p id="map-caption"></p></div><form method="dialog" class="modal-backdrop"><button aria-label="Chiudi mappa">Chiudi</button></form></dialog></body></html>`;}
