import {nationalHeroMap} from './redesign-maps.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {h, shell} from './redesign-lib.mjs';

const number = value => Number(String(value).match(/-?\d+(?:[.,]\d+)?/)?.[0]?.replace(',', '.'));
export async function loadMilano(root) {
  const source = JSON.parse(await fs.readFile(path.join(root, 'data/milano.json'), 'utf8'));
  assert.equal(source.city, 'Milano');
  assert.equal(source.hourly.length, 19);
  assert.equal(source.daily.length, 7);
  const hourly = source.hourly.map(row => ({...row, temperatureC:number(row.temperature), feelsLikeC:number(row.feelsLike),
    windKmh:number(row.windSpeed), gustKmh:number(row.gustSpeed),
    precipitationText:row.precipitation === '- assenti -' ? 'Assenti' : row.precipitation}));
  const daily = source.daily.map(day => ({...day, minimumC:number(day.minimum), maximumC:number(day.maximum),
    forecastReliabilityPercent:day.reliability ? number(day.reliability) : null,
    hourly:hourly.filter(row => row.date === day.date).map(row => row.id)}));
  assert.ok(hourly.every(row => Number.isFinite(row.temperatureC) && row.detail.fields.length === 12));
  return {...source, hourly, daily};
}

const fields = row => `<dl class="detail-grid">${row.detail.fields.map(field => `<div><dt>${h.esc(field.label)}</dt><dd>${h.esc(field.value)}</dd></div>`).join('')}</dl>`;
const rain = row => h.esc(row.precipitationText);
function fullTable(rows, interval) {
  return `<div data-interval="${interval}"><p class="table-scroll-note note">Su schermo stretto, scorri orizzontalmente per leggere tutte le colonne.</p><div class="overflow-x-auto" role="region" aria-label="Milano · previsioni a ${interval} ore" tabindex="0"><table class="table data-table hourly-secondary-table"><caption>Milano · intervalli di ${interval} ${interval === 1 ? 'ora' : 'ore'}</caption><thead><tr><th scope="col">Data e ora</th><th scope="col">Condizioni</th><th scope="col">Temperatura</th><th scope="col">Precipitazioni</th><th scope="col">Vento</th></tr></thead><tbody>${rows.map(row => `<tr data-row="${row.id}"><th scope="row"><button class="btn btn-ghost row-hour" data-hour="${row.id}" data-show-detail aria-controls="hour-detail">${h.esc(h.date(row.date, true))} · ${row.time}</button></th><td>${h.esc(row.condition)}</td><td>${h.temp(row.temperatureC)}</td><td>${rain(row)}</td><td>${h.esc(row.windDirection)} · <span data-kmh="${row.windKmh}">${row.windKmh} km/h</span><br>Raffiche <span data-kmh="${row.gustKmh}">${row.gustKmh} km/h</span></td></tr>`).join('')}</tbody></table></div></div>`;
}

export async function buildMilano(root, d) {
  const b = d.milano;
  const first = b.hourly.filter(row => row.intervalHours === 1 && row.date === b.date).slice(0, 4);
  const tomorrow = b.daily[1];
  const later = b.hourly.filter(row => row.intervalHours === 1 && !first.includes(row));
  const threeHour = b.hourly.filter(row => row.intervalHours === 3);
  const selected = first[0];
  const body = `<div class="forecast-layout"><div class="local-primary"><div class="city-heading"><h1>Milano</h1><p>${h.esc(h.date(b.date))}</p></div>
<div class="hour-line" role="group" aria-label="Seleziona un’ora del ${h.esc(h.date(b.date, true))}">${first.map((row, index) => `<button class="btn btn-ghost hour-pick" data-hour="${row.id}" aria-pressed="${index === 0}">${row.time}</button>`).join('')}</div>
<div class="selected-hour" aria-live="polite"><span id="selected-time">Ore ${selected.time}</span><span id="selected-symbol">${h.symbol(d, selected.symbol)}</span><strong id="selected-temp">${h.temp(selected.temperatureC)}</strong><span id="selected-condition">${h.esc(selected.condition)}</span></div>
<h2 class="hours-heading">Le prossime ore</h2><div class="overflow-x-auto essential-table-scroll" role="region" aria-label="Milano · previsioni delle prossime ore" tabindex="0"><table class="table hourly-table"><caption class="sr-only">Milano · ${h.esc(h.date(b.date))} · previsioni a intervalli di un’ora</caption><thead><tr><th scope="col">Ora</th><th scope="col">Temperatura</th><th scope="col">Precipitazioni</th></tr></thead><tbody>${first.map((row,index) => `<tr data-row="${row.id}"${index === 0 ? ' class="selected"' : ''}><th scope="row"><button class="btn btn-ghost row-hour" data-hour="${row.id}" data-show-detail aria-controls="hour-detail">${row.time}<span class="sr-only"> · dettagli di Milano</span></button></th><td>${h.temp(row.temperatureC)}</td><td>${rain(row)}</td></tr>`).join('')}</tbody></table></div>
<section class="tomorrow-preview" aria-labelledby="tomorrow-title"><h2 id="tomorrow-title">Milano · domani</h2><p>${h.esc(h.date(tomorrow.date))}</p><div class="daily-summary"><div><span>Minima</span><strong>${h.temp(tomorrow.minimumC)}</strong></div><div><span>Massima</span><strong>${h.temp(tomorrow.maximumC)}</strong></div><div><span>Attendibilità</span><strong>${tomorrow.forecastReliabilityPercent ?? '—'}${tomorrow.forecastReliabilityPercent === null ? '' : '%'}</strong></div><a class="link" href="#giorni">Consulta domani <span aria-hidden="true">→</span></a></div><p class="note">Attendibilità giornaliera non pubblicata nel riepilogo acquisito.</p></section></div>
<aside class="national-preview" aria-labelledby="national-title"><h2 id="national-title">Italia · ${h.esc(h.date(d.national.date, true))}</h2><p class="national-date">${h.esc(h.date(d.national.date))}</p>${h.figure(nationalHeroMap(d.national.fullDayMap), `Fonte iLMeteo · ${h.date(d.national.date)} · grafica ridisegnata`, 'compact-map')}<p class="national-teaser">${h.esc(d.national.summary.text)}</p><a class="link national-action" href="domani.html">Previsioni nazionali <span aria-hidden="true">→</span></a><p class="note">Bollettino nazionale dell’edizione acquisita l’8 ottobre. Milano è acquisita separatamente il 9 ottobre.</p></aside></div>
<section class="hour-detail" id="hour-detail" hidden aria-live="polite"><h2 tabindex="-1">Milano · ${selected.time}</h2>${fields(selected)}</section>
<section class="section" aria-labelledby="more-hours"><h2 id="more-hours">Gli altri orari acquisiti</h2><p>Le ore dopo mezzanotte appartengono al giorno successivo. L’ora originale 24 è mostrata come 00:00. Gli intervalli di una e tre ore mantengono i rispettivi valori e dettagli.</p><div class="controls unit-tools"><label for="temp-unit">Temperatura <select class="select" id="temp-unit"><option value="C">Celsius · °C</option><option value="F">Fahrenheit · °F</option></select></label><label for="wind-unit">Vento <select class="select" id="wind-unit"><option value="kmh">Chilometri orari · km/h</option><option value="kn">Nodi</option></select></label><label for="hour-interval">Intervallo <select class="select" id="hour-interval"><option value="1">1 ora</option><option value="3">3 ore</option></select></label></div><p class="note" id="interval-status" role="status">${b.hourly.filter(row => row.intervalHours === 1).length} previsioni a un’ora e ${threeHour.length} previsioni a tre ore.</p>${fullTable(later,1)}${fullTable(threeHour,3)}
${h.details('Tutti i dettagli originali', b.hourly.map(row => h.details(`${h.date(row.date, true)} · ${row.time} · ${row.intervalHours} h · ${row.condition}`, fields(row))).join(''))}</section>
<section class="section" id="giorni" aria-labelledby="days-title"><h2 id="days-title">Milano nei prossimi giorni</h2><p>I sette riepiloghi appartengono all’edizione di Milano del ${h.esc(h.date(b.date, true))}. Le ore acquisite coprono soltanto una parte delle giornate.</p><div class="controls"><label for="forecast-day">Leggi il riepilogo <select class="select" id="forecast-day" aria-controls="day-summary">${b.daily.map(day => `<option value="${day.date}"${day === tomorrow ? ' selected' : ''}>${h.esc(h.date(day.date))}</option>`).join('')}</select></label></div><div id="day-summary" role="status"><p>${h.esc(h.date(tomorrow.date))} · minima ${h.temp(tomorrow.minimumC)} · massima ${h.temp(tomorrow.maximumC)}</p></div><div class="overflow-x-auto" role="region" aria-label="Sette riepiloghi giornalieri di Milano" tabindex="0"><table class="table data-table"><caption>Milano · riepiloghi acquisiti</caption><thead><tr><th scope="col">Giorno</th><th scope="col">Minima</th><th scope="col">Massima</th><th scope="col">Attendibilità</th></tr></thead><tbody>${b.daily.map(day => `<tr><th scope="row"><time datetime="${day.date}">${h.esc(h.date(day.date,true))}</time></th><td>${h.temp(day.minimumC)}</td><td>${h.temp(day.maximumC)}</td><td>${day.forecastReliabilityPercent === null ? 'Non fornita' : day.forecastReliabilityPercent + '%'}</td></tr>`).join('')}</tbody></table></div></section>
<section class="section" aria-labelledby="source-bulletin"><h2 id="source-bulletin">Il bollettino e le informazioni di Milano</h2><p class="note">${h.esc(b.update)} · ${h.esc(b.author)} · dati acquisiti e congelati</p>${b.sections.map(section => h.details(section.title, `<p>${h.esc(section.text)}</p>${section.links.length ? `<ul class="link-list">${section.links.map(link => `<li>${h.link({...link,availability:'external'})}</li>`).join('')}</ul>` : ''}`, section.title.startsWith('Meteo di'))).join('')}</section>
<section class="section" aria-labelledby="observation-title"><h2 id="observation-title">Ultima rilevazione acquisita</h2>${b.realtime.map(row => `<p>${h.esc(h.date(b.date))} · ore ${h.esc(row.time)}. Dato acquisito, separato dalle previsioni.</p><dl class="detail-grid">${Object.entries({Temperatura:row.temperature + ' °C','Temperatura percepita':row.feelsLike + ' °C',Pressione:row.pressure + ' mb','Umidità relativa':row.humidity + '%',Visibilità:row.visibility,Grandine:row.hail,'Indice UV':row.uv,'Quota 0°C e neve':row.freezingLevel}).map(([label,value]) => `<div><dt>${h.esc(label)}</dt><dd>${h.esc(value)}</dd></div>`).join('')}</dl>`).join('')}</section>
<section class="section"><h2>Fonte dell’acquisizione</h2><p>Materiali iLMeteo e rispettivi autori, conservati per l’esercitazione locale. La copia non riceve aggiornamenti né previsioni delle altre località.</p><ul class="link-list"><li>${h.link({label:'Milano sul sito ufficiale',href:b.source.url,availability:'external'})}</li><li><a class="link" href="../sources/milano-manifest.json">Provenienza della pagina</a></li><li><a class="link" href="../assets/milano-manifest.json">Fonti e hash degli asset</a></li></ul></section>`;
  await fs.writeFile(path.join(root, 'redesign/milano.html'), shell(d, 'milano', 'Meteo Milano', body));
}
