import '@fontsource/inter/latin-400.css'
import '@fontsource/inter/latin-500.css'
import '@fontsource/inter/latin-600.css'
import '@fontsource/inter/latin-700.css'
import '@fontsource/merriweather/latin-400.css'

import './daisy-built.css'
import './tokens.css'
import './slides.css'
import './components.css'
import './grades.css'
import './motion.css'
